// Handles the nano commands
function handleNano(message){
    const randomMessage =[
    "OMG You're sooo tinnnyyyyyy... 😂😂",
    "Whaa who's that? I can't see anyone...",
    "Did someone say something? Oh, it's just your tiny text popping up!",
    "Hey there, little buddy! Did you need a boost to reach the keyboard?",
    "Aww, did someone shrink the font size again?",
    "I'll need a magnifying glass to read your messages! 😄",
    "You're so tiny, I almost mistook you for an emoji! 🤏",
    "Looks like we've got a fun-sized message from you!",
    "Can you speak up? I think your text got lost in the pixels!",
    "Your messages are like hidden treasures, I have to search for them!",
    "It's like your words are playing hide and seek in the chat!",
    "Hey, it's not the size of the text that matters, it's the message behind it!",
    "Tiny but mighty, right?",
    "I've seen ants with bigger fonts!",
    "Are you communicating in Morse code or something?",
    "Did you type that from a smartwatch?",
    "You're like a whisper in the wind of the chat!",
    "Is this the fine print section?",
    "I think I need my reading glasses for your messages!",
    "I'll need a telescope to read this properly!",
    "I had to zoom in to see your text!",
    "I think your text got lost in the emoji jungle!",
    "I'll put on my detective hat to decipher your message!",
    "It's like you're texting from the land of Lilliput!",
    "You're like a pixel in the vast screen of chat!",
    "Do you need a ladder to send messages?",
    "It's like I'm reading secret code!",
    "Are you using invisible ink?",
    "I think you're whispering through the chat!",
    "You're the real MVP of short messages!",
    "Can you send Morse code? It might be easier to read!",
    "I bet you're the king/queen of concise writing!",
    "Every character counts, right?",
    "You're like a haiku poet of the chat!",
    "Did you send a message or was that just a blink?",
    "Your messages are like little surprises!",
    "You're like the highlighter in the book of chat!",
    "I think I need a magnifying glass for this!",
    "Short, sweet, and straight to the point!",
    "Your messages are like tiny puzzle pieces!",
    "I'll need to put on my glasses for this mini-text!",
    "You're the epitome of brevity!",
    "Your messages are like little gems in the chat!",
    "Blink once if you need assistance with the keyboard!",
    "You're like a small font in a big world!",
    "I'll have to squint to read this!",
    "I feel like I'm reading a message in a bottle!",
    "Your messages are like tiny firecrackers!",
    "Short, but definitely not lacking in impact!",
    "You're the minimalist champion of the chat!",
    "Your messages are like Easter eggs in the chat!",
    "Blink twice if you're typing blindfolded!",
    "Your messages are like breadcrumbs in the chat!",
    "I'll have to decode this message like a cryptographer!",
    "You're like the secret agent of the chat with your covert messages!",
    "Short messages, big personality!",
    "You're like the telegraph operator of the chat!",
    "I think your messages need a passport to travel!",
    "Your messages are like tiny stars in the chat galaxy!",
    "Are you practicing for the Twitter character limit?",
    "Your messages are like little riddles!",
    "You're the whisperer of the chat!",
    "Short and snappy, just the way we like it!",
    "You're like the bonsai tree of messaging!",
    "Your messages are like little post-it notes in the chat!",
    "You're like the acrobat of concise communication!",
    "Your messages are like little fireworks in the chat!",
    "Short on words, but not on impact!",
    "You're the maestro of minimalism!",
    "Your messages are like tiny snowflakes in the chat!",
    "Short and sweet, just like your messages!",
    "You're the Picasso of brevity!",
    "Your messages are like little raindrops in the chat!",
    "Short and to the point, that's the spirit!",
    "You're the ninja of succinctness!",
    "Your messages are like little shooting stars in the chat!",
    "Keep 'em short, keep 'em coming!",
    "You're like the sprinter of messaging!",
    "Your messages are like little butterflies in the chat!",
    "Short, but definitely not lacking in charm!",
    "You're like the haiku master of the chat!",
    "Your messages are like little paper airplanes in the chat!",
    "Short messages, big impact!",
    "You're like the sprinter of conversation!",
    "Your messages are like little whirlwinds in the chat!",
    "Short, but oh-so-memorable!",
    "You're like the poet laureate of brevity!",
    "Your messages are like little confetti in the chat!",
    "Short, but definitely not lacking in style!",
    "You're like the speed demon of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short messages, big personality!",
    "You're like the wordsmith of efficiency!",
    "Your messages are like little sunbeams in the chat!",
    "Short and snappy, just like you!",
    "You're like the lightning bolt of conversation!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little gems in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of communication!",
    "Your messages are like little miracles in the chat!",
    "Short and succinct, just the way we like it!",
    "You're like the ninja of conversation!",
    "Your messages are like little delights in the chat!",
    "Short, but definitely not lacking in impact!",
    "You're like the magician of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the poet of brevity!",
    "Your messages are like little gems in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the sprinter of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the wordsmith of conciseness!",
    "Your messages are like little beams of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the ninja of brevity!",
    "Your messages are like little rays of light in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your messages!",
    "You're like the magician of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short and snappy, just like your style!",
    "You're like the poet of succinctness!",
    "Your messages are like little pearls in the chat!",
    "Short, but definitely not lacking in wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your personality!",
    "You're like the ninja of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in charm!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little gems in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of conversation!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the sprinter of brevity!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the ninja of conciseness!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the sprinter of conversation!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of messaging!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of texting!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of conversation!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the wordsmith of brevity!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the hummingbird of messaging!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the poet of brevity!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the sprinter of messaging!",
    "Your messages are like little treasures in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the magician of brevity!",
    "Your messages are like little sparks in the chat!",
    "Short, but definitely not lacking in creativity!",
    "You're like the ninja of messaging!",
    "Your messages are like little rays of sunshine in the chat!",
    "Short and snappy, just like your spirit!",
    "You're like the poet of messaging!",
    "Your messages are like little bursts of joy in the chat!",
    "Short and sweet, just like your style!",
    "You're like the sprinter of brevity!",
    "Your messages are like little nuggets of gold in the chat!",
    "Short, but definitely not lacking in personality!",
    "You're like the hummingbird of conversation!",
    "Your messages are like little pearls in the chat!",
    "Short and snappy, just like your wit!",
    "You're like the magician of messaging!",
    "Your messages are like little sparks in the chat!",
    "Short and sweet, just like your charm!",
    "You're like the poet of brevity!",
    "Your messages are like little treasures in the chat!",
    "Short, but definitely not lacking in creativity!",
    ]

    message.reply({
            content:
            randomMessage[Math.floor(Math.random() * randomMessage.length)],
    })
    message.react('😃');

}

module.exports={
    handleNano
}